global simplify boostrap script

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -1,47 +1,45 @@
 #!/usr/bin/env zsh
-script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
-
 log() {
-    if [[ $dry_run == "1" ]]; then
-        echo "[DRY_RUN]: $1"
-    else
-        echo "$1"
-    fi
+    echo "$1"
 }
 
 log "Update system && install core packages"
-if [[ $dry_run == "0" ]]; then
-    # Verify that we are running not as root
-    if [[ $EUID -eq 0 ]]; then
-        echo "This script should not be run as root"
-        exit 1
-    fi
-
-    if [[ -z "$HOME" ]]; then
-        echo "HOME env var is not set"
-        exit 1
-    fi
-
-    sudo apt update && sudo apt upgrade
-
-    # Initial git setup
-    git submodule init && git submodule sync
-    git submodule update
-    git config --global user.email "inom@iturdikulov.com"
-    git config --global user.name "Inom Turdikulov"
-
-    # Minimal install of most required packages
-    sudo apt install -y yadm wget2 build-essential curl ca-certificates git jq
-    sudo apt install -y firmware-linux firmware-linux-nonfree
-
-    if [ $? -ne 0 ]; then
-      echo "Failed to update system, check logs above and try to fix all issues."
-      exit 1
-    fi
+# Verify that we are running not as root
+if [[ $EUID -eq 0 ]]; then
+echo "This script should not be run as root"
+exit 1
 fi
 
-$script_dir/runs/_libs
+if [[ -z "$HOME" ]]; then
+echo "HOME env var is not set"
+exit 1
+fi
 
-log "RUNs, go to run dir and execute additional runners: "
-find $script_dir/runs -mindepth 1 -maxdepth 1 -executable
+sudo apt update && sudo apt upgrade
 
+# Because Git submodule commands cannot operate without a work tree, they must
+# be run from within $HOME (assuming this is the root of your dotfiles)
+cd "$HOME"
+yadm submodule update --recursive --init
+cd "$OLDPWD"
+
+git config --global user.email "i@inomoz.ru"
+git config --global user.name "Inom T."
+
+# Minimal install of most required packages
+sudo apt install -y yadm wget2 build-essential curl ca-certificates git jq
+sudo apt install -y firmware-linux firmware-linux-nonfree
+
+if [ $? -ne 0 ]; then
+  echo "Failed to update system, check logs above and try to fix all issues."
+  exit 1
+fi
+
+echo "Decrypt some config files"
+yadm decrypt
+
+# TODO: move into own runner
+echo "Remove discover update notifier"
+sudo rm "/etc/xdg/autostart/org.kde.discover.notifier.desktop"
+
+echo "Now go to ~/.config/yadm/runs and execute required"
