Global update:
- add new config files
- nvim moved into own repo
- adjust runners

diff --git a/.config/yadm/runs/fonts b/.config/yadm/runs/fonts
--- a/.config/yadm/runs/fonts
+++ b/.config/yadm/runs/fonts
@@ -2,12 +2,20 @@
 
 sudo apt install -y fonts-firacode fonts-terminus
 
+if [[ $(hostname) == "volga" ]]; then
+    echo 'font=Monospace:size=18' > "$HOME/.config/foot/foot.local.ini"
+else
+    echo 'font=Terminess Nerd Font Mono:size=16.5,Monospace:size=16' > "$HOME/.config/foot/foot.local.ini"
+fi
+
 # Download Terminus Nerd Font (tar.xz)
 OUTPUT_FILE=/tmp/terminus.tar.xz
 
 ! [ -f "$OUTPUT_FILE" ] && wget2 -O $OUTPUT_FILE "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/Terminus.tar.xz" \
 || echo "$OUTPUT_FILE already exist, skip downloading"
 
+# Terminus
+#
 # Verify
 SHA_SUM=$(sha256sum "$OUTPUT_FILE")
 echo "e857b18a99701528f873275b6012792caf6e30c34c512ee92cda51520140054f" "$OUTPUT_FILE" | sha256sum -c || { echo "Invalid sha $SHA_SUM for $OUTPUT_FILE, skip installing font"; exit 1; }
@@ -17,3 +25,20 @@ mkdir -p "$HOME/.local/share/fonts/Terminus"
 tar -xf /tmp/terminus.tar.xz -C "$HOME/.local/share/fonts/Terminus" && rm "$OUTPUT_FILE"
 fc-cache -fv
 echo "Terminus Nerd Font installed."
+
+# Commit Mono
+#
+# Download Commit Mono Font (tar.xz)
+OUTPUT_FILE=/tmp/commit_mono.tar.xz
+
+# Verify
+! [ -f "$OUTPUT_FILE" ] && wget2 -O $OUTPUT_FILE "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/CommitMono.tar.xz" \
+|| echo "$OUTPUT_FILE already exist, skip downloading"
+SHA_SUM=$(sha256sum "$OUTPUT_FILE")
+echo "44cdabae7708de3548fdd78ed59cdbb1fedbca18e16644047ed4a23623a530ca" "$OUTPUT_FILE" | sha256sum -c || { echo "Invalid sha $SHA_SUM for $OUTPUT_FILE, skip installing font"; exit 1; }
+
+# Create font directory
+mkdir -p "$HOME/.local/share/fonts/CommitMono"
+tar -xf /tmp/commit_mono.tar.xz -C "$HOME/.local/share/fonts/CommitMono" && rm "$OUTPUT_FILE"
+fc-cache -fv
+echo "Commit Mono Font installed."
