move glow dependency into apt source

diff --git a/.config/yadm/runs/go b/.config/yadm/runs/go
--- a/.config/yadm/runs/go
+++ b/.config/yadm/runs/go
@@ -11,16 +11,13 @@ rm "/tmp/go_$VERSION.tar.gz"
 echo "set correct GOPATH and PATH in your shell!"
 export GOPATH=$HOME/.local/go
 
-cd /usr/local/go/bin/
+cd /usr/local/go/bin/ || { echo "Failed"; exit 1; }
 
 # Install gopls lang server
 ./go install golang.org/x/tools/gopls@latest
-
-# Install Glow: render markdown on the CLI, with pizzazz!
-# TODO: future, maybe aviable in repo, https://packages.debian.org/unstable/main/glow
-./go install github.com/charmbracelet/glow@latest
 
 # Dev tools
 ./go install golang.org/x/tools/cmd/goimports@latest
 ./go install mvdan.cc/sh/v3/cmd/shfmt@latest
 ./go install github.com/xjasonlyu/tun2socks/v2@latest
+./go install github.com/antonmedv/countdown@latest
